name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag abbhavani11/samplewebserver:v0.${{ github.run_number }}

  docker_login:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

  push_to_docker_hub:
    runs-on: ubuntu-latest
    needs: [build, docker_login]
    steps:
    - name: Push image to Docker Hub
      run: docker push abbhavani11/samplewebserver:v0.${{ github.run_number }}
